import { SHOP_ITEM_GROUP } from './models'

export const SHOP_GROUP_COLOR = {
  [SHOP_ITEM_GROUP.BAKERY]: '#00005c',
  [SHOP_ITEM_GROUP.DAIRY]: '#6a097d',
  [SHOP_ITEM_GROUP.MEAT]: '#c060a1',
  [SHOP_ITEM_GROUP.FRUITS_AND_VEGGIES]: '#e71414',
  [SHOP_ITEM_GROUP.DRINKS]: '#7c3c21',
  [SHOP_ITEM_GROUP.CLEANING]: '#0e9aa7',
  [SHOP_ITEM_GROUP.SPICES]: '#3da4ab',
  [SHOP_ITEM_GROUP.USER_DEFINED]: '#fe8a71',
  [SHOP_ITEM_GROUP.OTHER]: '#2fc4b2',
}
